### ISSUE TITLE
CMake 3.0.2 fails when building for Android

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#126]
Failure related to the fact that before a certain version (3.2?) CMake defined the SYSTEM_NAME on Android as Linux, not Android, so this file https://github.com/OSVR/OSVR-Core/blob/master/cmake/PlatformDefinitions.cmake fails to set up the header right.

h/t @janoc for finding this one.

**Comment by rpavlik** [comment]
I have "worked around" this at the OSVR-Android-Build level with documenting this: https://github.com/OSVR/OSVR-Android-Build/commit/10d37f52a58a261d8c7e39d947934e575fad4810#diff-04c6e90faac2675aa89e2176d2eec7d8R13

Not sure if that's sufficient, or if we should be enforcing the higher version

**Comment by janoc** [comment]
I would at least check the CMake version when building for Android and emit a warning/error there. There is no need to require higher version for other platforms. Otherwise the dev could miss that req ("hey, it compiled fine for Windows!") and waste a lot of time tracking this down - it is not really obvious from the error messages what is going on. 

Alternatively, this could be perhaps fixed by changing those #ifdefs in the USBSerial library - nothing else seems to be using these macros.

**Comment by rpavlik** [comment]
Well, and that library is actually being skipped right now in the build for Android.

**Comment by janoc** [comment]
I have managed to build it without issues once the CMake problem was found. If you want to run servers on Android, that lib could be useful.

**Comment by rpavlik** [comment]
Yeah, the trouble is that the header/interface used by the Linux version of that code isn't included before Lollipop, so we'd need to write an android-specific version - see https://github.com/OSVR/OSVR-Core/issues/125
