### ISSUE TITLE
"Recenter"/"Reset Yaw" client API

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#182]
See #97 for the discussion leading to this issue.

I personally don't think it's a good idea to effectively put the current app behind an API call, since it adjusts one device's calibration WRT the system-wide ("room") coordinate system, which will be very problematic for positional tracking, sensor fusion, multiple tracked devices, etc: the effect ("facing this way should be forward in the game world") desired is really a change in the room-world transform, not the HMD-room calibration transform.

Developers used to the Oculus SDK are used to having this functionality available, apparently because of drifty hardware sensors and an SDK design that does not maintain a consistent calibration between applications. This is apparently the source of the pressure to include such an API. If we end up having to do this, we should do it "right" (at a higher level in the transform tree, presumably as a part of improving/making more explicit the transform hierarchy in the core) to avoid no end of headaches.

**Comment by russell-taylor** [comment]
There is an optional parameter in the RenderManager program to insert a roomToWorld space after the existing transform tree.  But thinking about this, even it will be a problem because it will get in the way of the transforms to the other within-OSVR spaces (hand, head, whatever) and there is not a clean way to know whether to apply it.  Either need to remove that or rethink it.  It is probably better for the app developer to put in a room space explicitly and then modify it than to have me tack it on for them at the end.

**Comment by rpavlik** [comment]
This is in, https://github.com/OSVR/OSVR-Core/commit/c378ce6ecbdf6d8be10ed2eb80b5f3b67f58cf6e

**Comment by peroht** [comment]
I suggest the developer should handle the room space master YPR node, then have a child node that ties to that whenever the developer need to correlate the local HDK reset and the master reset.
