### ISSUE TITLE
osvr_server aborts when compiled with GCC 4.8.x std::regex not implemented

### ISSUE THREAD

**Issue by sradigan** [OSVR/OSVR-Core#416]
This issue was reported by @mastykin via [Gitter Chat](https://gitter.im/OSVR/OSVR-Core) Apr 05 04:51

Due to commit: f1a4a5925a1435121ac627ed328a557506850a02

The problematic line [here](https://github.com/OSVR/OSVR-Core/commit/f1a4a5925a1435121ac627ed328a557506850a02#diff-70e08093f3a7f07622db0c7a46db78c9R95)

The use of std::regex is not implemented in GCC 4.8.x (see references)

Upgrading to GCC 4.9.x or higher will resolve the issue.

The code will not fail to compile, it will fail at runtime as follows:

```
./osvr_server
[OSVR Server] Using default config file - pass a filename on the command line to use a different one.
[OSVR Server] Using config file 'osvr_server_config.json'
[OSVR Server] Constructing server as configured...
[OSVR Server] Loading auto-loadable plugins...
[OSVR Server] Loading plugins...
[OSVR Server]
[OSVR Server] Instantiating configured drivers...
[OSVR Server]
terminate called after throwing an instance of 'std::regex_error'
what(): regex_error
Aborted (core dumped)
```

GDB backtrace: http://pastebin.com/PLux4MeT

References:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53631
http://stackoverflow.com/questions/20027305/strange-results-when-using-c11-regexp-with-gcc-4-8-2-but-works-with-boost-reg
http://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions

**Comment by rpavlik** [comment]
Oh, rats. can't even compile-time detect it. We're not doing anything too complex with that code (It's just trying to figure out what got passed: does it end with `:portnum`? does it have some weird thing like `tcp://` in it?), so that we can normalize the most common cases. So it could presumably be fairly easily re-written to not use a regex and or use alternate regex libraries (less desireable since IIRC boost regex isn't header only). I would like to keep GCC 4.8 usable.

I suppose this would be an argument for putting these little utility functions (not just the containers and essential utilities) in some separate place and unit testing them like crazy, though I don't know which of the various builders run the tests.

Happy to accept help on this one - I'd have to go digging through refs to see if there's a good string member function to solve this in an efficient way (since it's like "find first not of" on a reversed string)

**Comment by russell-taylor** [comment]
I think there is code to parse things like this in VRPN.  It was written before the regex stuff came into C++.

**Comment by sradigan** [comment]
The code in VRPN does not seem to be quite as robust, but it should work fine on expected input cases.

I believe this is the code to get the port number:
https://github.com/vrpn/vrpn/blob/e75e92c11ac7aef840a29755d33606a4f338fba4/vrpn_Connection.C#L6419

**Comment by russell-taylor** [comment]
When this crashes for me on gcc 4.8.4, it is throwing an exception for a non-matching bracket.  Removing the brackets from the expression makes the code run (but not work correctly), so it looks like maybe there is an implementation that is broken or we're not properly escaping some character...

**Comment by russell-taylor** [comment]
Fixed in https://github.com/OSVR/OSVR-Core/pull/481 by replacing the regex code with std::string and isdigit() function.  This issue can be closed when the pull request is merged.

**Comment by sradigan** [comment]
I was just going through some old issues, I am going to close this out since the linked pull was merged. No testing to make sure that this was resolved happened, it just seemed stale.
