### ISSUE TITLE
opencv_core-NOTFOUND

### ISSUE THREAD

**Issue by djdevin** [OSVR/OSVR-Core#430]
Trying to build on Fedora 23, during `make`

```
Scanning dependencies of target com_osvr_VideoCapture_OpenCV
[ 32%] Building CXX object plugins/opencv/CMakeFiles/com_osvr_VideoCapture_OpenCV.dir/com_osvr_VideoCapture_OpenCV.cpp.o
make[2]: *** No rule to make target 'opencv_core-NOTFOUND', needed by 'lib64/osvr-plugins-0/com_osvr_VideoCapture_OpenCV.manualload.so'.  Stop.
CMakeFiles/Makefile2:3039: recipe for target 'plugins/opencv/CMakeFiles/com_osvr_VideoCapture_OpenCV.dir/all' failed
make[1]: *** [plugins/opencv/CMakeFiles/com_osvr_VideoCapture_OpenCV.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

Cmake 3, OpenCV is installed:

```
opencv-devel-2.4.12.3-1.fc23.x86_64
opencv-2.4.12.3-1.fc23.x86_64
opencv-core-2.4.12.3-1.fc23.x86_64
```

**Comment by rpavlik** [comment]
Did CMake actually find OpenCV correctly on its own? I'd imagine it should be able to, that version looks OK.  You can work around it by setting `BUILD_WITH_OPENCV` to off, but I'd suspect something distro-specific with how they are installing the CMake config files for OpenCV. (We do need more than just the core module...)

**Comment by Dmi3Dev** [comment]
I'm on Fedora 23 and also have opencv installed (same version as described above) and also got same error. 
cmake didn't seem to look for opencv (although I don't know if it should show during make generation)
`$ sudo cmake ..                                                                              
-- Git reports version 0.6-1194-g0c54f5e                                                                           
-- Found OpenGL: /lib64/libGL.so  
-- Found SDL2: /lib64/libSDL2.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found JsonCpp: /usr/local/lib/cmake/jsoncpp  
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Performing Test OSVR_HAVE_STD_SHARED_PTR
-- Performing Test OSVR_HAVE_STD_SHARED_PTR - Success
-- Performing Test OSVR_HAVE_STD_UNIQUE_PTR
-- Performing Test OSVR_HAVE_STD_UNIQUE_PTR - Success
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   date_time
--   chrono
--   program_options
--   filesystem
-- Found PythonInterp: /bin/python (found version "2.7.11") 
-- Git's description of the current revision indicates this is a prerelease of 07.34: version_07.33-310-ge75e92c

-- Configuring the VRPN suite version 07.34.0~prerelease-git-07.33-310-ge75e92c using the CMake-based build system

-- Checking for module 'libusb-1.0'
--   Found libusb-1.0, version 1.0.20
-- Found Libusb1: /lib64/libusb-1.0.so  
-- Looking for C++ include linux/joystick.h
-- Looking for C++ include linux/joystick.h - found
-- Looking for C++ include linux/input.h
-- Looking for C++ include linux/input.h - found
-- Found quatlib: quat  
-- Performing Test OSVR_HAVE_STRUCT_TIMEVAL_IN_SYS_TIME_H
-- Performing Test OSVR_HAVE_STRUCT_TIMEVAL_IN_SYS_TIME_H - Success
-- Performing Test OSVR_HAVE_STRUCT_TIMEVAL_IN_WINSOCK2_H
-- Performing Test OSVR_HAVE_STRUCT_TIMEVAL_IN_WINSOCK2_H - Failed
-- Looking for std::align
-- Looking for std::align - found
-- Generating /home/dmi3/_DEV/CPP/rnd/OSVR-Core/build/src/osvr/Util/ReportTypesX.h
-- Performing Test SUPPORTS_W_FLAG
-- Performing Test SUPPORTS_W_FLAG - Success
-- Performing Test SUPPORTS_WALL_FLAG
-- Performing Test SUPPORTS_WALL_FLAG - Success
-- Performing Test SUPPORTS_WEXTRA_FLAG
-- Performing Test SUPPORTS_WEXTRA_FLAG - Success
-- Performing Test SUPPORTS_WNO_MAYBE_UNINITIALIZED_FLAG
-- Performing Test SUPPORTS_WNO_MAYBE_UNINITIALIZED_FLAG - Success
-- Generating /home/dmi3/_DEV/CPP/rnd/OSVR-Core/build/src/osvr/Util/ClientCallbackTypesC.h
-- Looking for intrin.h
-- Looking for intrin.h - not found
-- Looking for byteswap.h
-- Looking for byteswap.h - found
-- Performing Test OSVR_HAVE_WORKING_MS_BYTESWAPS
-- Performing Test OSVR_HAVE_WORKING_MS_BYTESWAPS - Failed
-- Performing Test OSVR_HAVE_WORKING_BSWAP
-- Performing Test OSVR_HAVE_WORKING_BSWAP - Failed
-- Performing Test OSVR_HAVE_WORKING_BSWAP_UNDERSCORE
-- Performing Test OSVR_HAVE_WORKING_BSWAP_UNDERSCORE - Success
-- Performing Test OSVR_HAVE_WORKING_UNDERSCORES_BSWAP
-- Performing Test OSVR_HAVE_WORKING_UNDERSCORES_BSWAP - Success
-- Could NOT find Markdown (missing:  MARKDOWN_EXECUTABLE) 
-- Configuring done
-- Generating done`

Then I opened project with CLion and was able to compile Debug version succesfully without changing anything, but it failed to compile Release on generated Makefile on line 160:
`# The main clean target
clean/fast: clean`

I was building ALL, since I'm not sure what need to be built at this point, it's my day one trying to work with OSVR. I'll post here if I'll be able to get it working. Not sure why wouldn't system see opencv when compiling in terminal, but it did find it, when using CLion.

**Comment by AlexRamallo** [comment]
@djdevin you could try changing the OpenCV Dir variable during cmake config, but I tried that myself with no success.

Also, idk if this would make a difference but I noticed that in Fedora 23 the OpenCV lib binaries are in /usr/lib64 rather than /usr/lib64/OpenCV. Although if it were a linking issue I don't see why the linker couldn't find the libraries if they're in /usr/lib64

**Comment by thaytan** [comment]
This is still broken for me in Fedora 25. A simply test like http://docs.opencv.org/2.4/doc/tutorials/introduction/linux_gcc_cmake/linux_gcc_cmake.html works fine, so it seems there's nothing intrinsically wrong with the OpenCV provided CMake files.

**Comment by andrewbenton** [comment]
I'm not sure how to get it to properly pick up the OpenCV libraries, but you can turn off OpenCV and get the rest of the build to complete.

**Comment by thaytan** [comment]
Confirming that moving the OpenCV find_libraries call up higher fixes the build for me on F25

**Comment by rpavlik** [comment]
This is the lovely imported-build-variant business - the downside of using cmake's package configuration files. #528 should fix this for now.
