### ISSUE TITLE
CMake fails as it wants to have a binary directory set to something other than the source dir despite CMAKE_BINARY_DIR being different.

### ISSUE THREAD

**Issue by UFeindschiff** [OSVR/OSVR-Core#555]
Just recursively cloned the master branch and ran cmake. (all libraries are installed as in the build instructions)
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib .`
and got the following error
`CMake Error at cmake/cmake-4.0.0-modules/RequireOutOfSourceBuild.cmake:41 (message):
  You must set a binary directory that is different from your source
  directory.  You might consider /home/ufeindschiff/OSVR-Core/build or
  /home/ufeindschiff/build-osvrcore
Call Stack (most recent call first):
  cmake/cmake-4.0.0-modules/autoinclude.cmake:13 (include)
  cmake/UseBackportedModules.cmake:92 (include)
  vendor/vrpn/CMakeLists.txt:15 (include)

-- Configuring incomplete, errors occurred!`

So I set CMAKE_BINARY_DIR thinking that it is speaking about that variable and ran
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BINARY_DIR=build .` yet it produces the same error. Therefore it seems like there is either a flaw in the CMakeLists or it is another variable that the script wants to differ from the "source directory", which I presume is CMAKE_SOURCE_DIR in which case it would be nice to have an output that actually tells you which CMake variable is the problem.

**Comment by rpavlik** [comment]
The issue here is that you're running CMake from the source directory - indicated by the ` .` at the end of your command line. Where you initially start CMake (if you're using command line) is the binary directory: the variable is just automatically set to match. When using the CMake GUI, you can "select" your binary directory right below where you select the source directory, hence the wording of the message.  In your case, do something like:

```bash
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib ..
```

and you'll have much more luck. You may need to remove a few CMake-generated files from your source directory before this will work - you should be able to see them with git status. (There is lots of information if you search for "cmake out of source build")

Good luck!
