### ISSUE TITLE
Make OSVR easier to submodule.

### ISSUE THREAD

**Issue by Armada651** [OSVR/OSVR-Core#69]
I think we need separate OSVR ClientKit and PluginKit repositories so these libraries can be more easily included as a submodule. Currently any git project that wants to use OSVR as a submodule has to clone the entire OSVR-Core repository.

The OSVR ClientKit should also be reduced in the amount of required dependencies if possible. I think it is unreasonable to depend on libraries such as OpenCV and Boost just to compile the Client API. The ClientKit should be as small as possible so it is easy to integrate and doesn't require to ship a lot of extra libraries just to access position and orientation data.

**Comment by rpavlik** [comment]
Sorry for the slow response on this one - was thinking on it a bit to see if I could come up with an easier solution before replying.

So boost and OpenCV are not required for consumers of the ClientKit API: they are used internally (in the libraries that back ClientKit and PluginKit), and are optional for clients wishing to use the C++ wrapper and C++ image support. However, if you're consuming OSVR via submodule and not via a built snapshot or an operating system package (debian package for instance), I can see that this distinction doesn't really matter since you're building the whole thing.

For now, it is useful to know that you can actually disable building of the server parts and only build the client. That doesn't reduce what you're building by a ton or deps very much (since there is a lot of shared code), but it does make it a little easier (and should make it easier than it does, see newly filed issue I cc'ed you on).

Trying to think if there's some useful way to separate clientkit and pluginkit (with their ostensibly small exposed dependencies) from the core (which does have internal dependencies), but I'm not sure there is one that would make it easier for your use case (where you want your dependencies as submodules) since ClientKit would still need to link against the stuff that actually implements it, which does have those deps.

**Comment by Armada651** [comment]
> Trying to think if there's some useful way to separate clientkit and pluginkit (with their ostensibly small exposed dependencies) from the core (which does have internal dependencies), but I'm not sure there is one that would make it easier for your use case (where you want your dependencies as submodules) since ClientKit would still need to link against the stuff that actually implements it, which does have those deps.

To be clear about the use case, I'm interested in building the ClientKit from source because pushing pre-compiled libraries to an open-source repository is generally frowned upon. Also since I am not using any of the Imaging APIs, I want to avoid having to include the OpenCV libraries which otherwise would result in having to submodule the OpenCV repository also.

The boost dependency is a lot easier to get through a review, but still a very large dependency unless we can make use of the modularity.

> So boost and OpenCV are not required for consumers of the ClientKit API: they are used internally (in the libraries that back ClientKit and PluginKit), and are optional for clients wishing to use the C++ wrapper and C++ image support.

I can see how boost is not required for consumers when just dealing with the headers of the C variant of the ClientKit API. But it looks like it is impossible to avoid it when building the implementation of the ClientKit itself. Though aren't all of the use cases of Boost within ClientKit already covered by the C++11 STL? Or is boost also required to compile the dependencies of the ClientKit?

Is it enough not to include the Imaging headers to avoid a dependency on OpenCV? Shouldn't the fact that this is optional be facilitated by the build system which currently lists it as a required dependency instead of an optional one?

> For now, it is useful to know that you can actually disable building of the server parts and only build the client. That doesn't reduce what you're building by a ton or deps very much (since there is a lot of shared code), but it does make it a little easier (and should make it easier than it does, see newly filed issue I cc'ed you on).

This does help, but still leaves you with a relatively large repository to submodule if you want to compile from source. Ofcourse if the shared dependencies are so numerous that splitting them wouldn't result in an effective reduction in the size of the repository then the current situation may be the better option.

**Comment by rpavlik** [comment]
I get your concern on binaries in open source.

Splitting the repo wouldn't result in much of a reduction in repo size. (VRPN is required in all cases, and while I could clean that repo up a bit, it wouldn't reduce the download size much if any, just the working copy size). However, I see that if you're wanting just the client, you're building as a submodule, and you don't want imaging, we could do some conditional compilation to exclude the core parts that require imaging support. I'd want to make sure the binaries were somehow marked (probably just a name change) so that they didn't get used in a place someone expected imaging support, but that sounds reasonable.

At the moment, build system complexity is pretty low and splitting would actually result in increasing it - since we have internal APIs that aren't exposed to external clients or plugins: keeping it in one build system means we can keep those hidden and not worry about exporting build parameters for them.

Boost is required to compile the core - C++11 doesn't cover it all. However, on open-source platforms (*nix/bsd) it should be pretty widespread, and there are actually Windows installers for it on their sourceforge page, though they aren't immediately obvious.

We'll keep this use case in mind - if more sophisticated server frontends are added, they'll be in a separate repo, for instance. I'll file an issue to be able to turn off OpenCV support if building just the client.

**Comment by Armada651** [comment]
> Boost is required to compile the core - C++11 doesn't cover it all.

And I take it the core is required to build the ClientKit?

> I'll file an issue to be able to turn off OpenCV support if building just the client.

When that dependency is out of the way I think I can make it work.

**Comment by rpavlik** [comment]
Yeah, the core is what ClientKit provides the interface for. Glad to hear we figured out a solution.

**Comment by rpavlik** [comment]
OK, so this is very nearly complete with the commits ending in https://github.com/OSVR/OSVR-Core/commit/533610fc62cfc95ee54c346774ff48f0330e612f - you can now turn on/off everything by group (server lib, server app, server plugins, server examples, client lib, client examples, client apps), and depending on what you choose, fewer Boost compiled libraries are needed for some configurations.

If you're OK with it, I'd like to close this issue, since we still have https://github.com/OSVR/OSVR-Core/issues/77 open for the only part that is not done here. Re-open if there's something we missed.

**Comment by Armada651** [comment]
That sounds great, can't wait for #77 to be fixed, then I can submit the Pull Request to merge OSVR support into the Dolphin Emulator.
